In [ ]:
import torch
import numpy as np

## 1. tensor 만들기
torch.tensor()

In [ ]:
torch.tensor(5)

In [ ]:
torch.tensor([1, 2, 3, 4, 5])

In [ ]:
torch.tensor([[1, 2], [4, 5], [5, 6]])
matrix1 = np.array(range(1, 10)).reshape(3, 3)
matrix2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix3 = torch.tensor(matrix1)
torch.from_numpy(matrix1)


In [24]:
torch.ones(size=(3, 3, 3))
torch.zeros(size=(3, 3, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.ones(size=(3, 3))

In [25]:
matrix = torch.tensor(np.array((range(1, 10))).reshape(3, 3))
#input은 반드시 tensor 형태여야 함
torch.ones_like(matrix)
torch.zeros_like(matrix)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

## arange 가능

In [29]:
torch.arange(8).reshape(2, 2, 2)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [40]:
torch.randn([5,5, 5, 5])

tensor([[[[ 2.5037e+00, -1.0484e+00,  2.2855e+00,  1.0453e+00, -1.2266e+00],
          [-8.3381e-01, -7.4259e-01,  1.9634e-01, -9.8006e-01,  2.8469e-01],
          [ 1.7017e-01,  3.3631e-02, -1.4056e-01,  1.9378e+00, -7.9103e-01],
          [ 4.9481e-01,  6.7880e-01,  4.6474e-01, -7.1108e-02,  7.3247e-01],
          [-6.8661e-01,  7.2579e-01, -1.3607e+00, -6.8808e-01, -1.3447e+00]],

         [[ 1.8462e+00,  1.0779e+00,  3.5198e-01, -3.0322e-01,  2.4028e-01],
          [-5.4411e-01, -1.4445e+00, -9.6947e-01, -1.0930e+00, -1.2937e+00],
          [-4.4286e-01, -5.0812e-01,  7.1981e-01,  6.8484e-01,  8.2955e-01],
          [-1.1365e+00,  1.8770e-01, -7.7379e-01, -7.7432e-01, -9.1018e-01],
          [ 1.9708e-01,  1.3639e-01,  3.9743e-01, -1.0370e+00,  1.7275e-01]],

         [[ 2.0179e+00,  1.0169e+00,  6.9531e-01,  2.6932e+00, -2.1225e-01],
          [-2.2107e+00, -2.7037e-02, -1.1898e+00, -1.1137e-01,  1.0980e+00],
          [ 4.2041e-01,  5.0662e-01,  1.4760e+00,  5.5836e-01,  6.4946e-

In [42]:
a = torch.tensor([1,2,3,4,5])
a.device

device(type='cpu')